[pytest]
markers =
    smoke: smoke tests
    sanity: sanity tests
    ui: ui tests
    functional: functional tests
    negative: negative tests
    boundary: boundary tests
    integration: integration tests
    errors_handling: error handling tests
    